spring:
  application:
    name: springboot-okta-1
 
server:
  port: 8081
  

okta:
  oauth2:
    issuer: https://dev-84453556.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaid2f9ptgX5LeIJ5d7
    client-secret: jGuc4hu45TWZU8kmMvwNqTSrZybrJ4lUHLsJ-WJf_FPmYwd5ued3Lcvo51w81EZH
    redirect-uri: /authorization-code/callback
    
    
    